#! /usr/bin/env ruby
require "pg"

DB = PG.connect(dbname:"expenses")

def display_help
	puts <<~HELP 
    An expense recording system

    Commands:

    add AMOUNT MEMO - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  HELP
end 

def list_expenses
	table = DB.exec("SELECT * FROM expenses ORDER BY created_on;")
	table.each do |tuple|
		cols = ["#{tuple["id"].rjust(3)}", 
			"#{tuple["created_on"]}",
			"#{tuple["amount"].rjust(12)}",
			"#{tuple["memo"]}"]
		puts cols.join(" | ")
	end
end

def add_expense(amnt, memo)
	memo = memo.gsub("'", "''")
	sql = "INSERT INTO expenses (amount, memo, created_on) VALUES (#{amnt}, '#{memo}', current_date)"
	DB.exec(sql)
end

command = ARGV[0]
if command == "list"
	list_expenses
elsif command == "add"
	if ARGV[1] && ARGV[2]
		amount = ARGV[1]
		memo = ARGV[2]
		add_expense(amount, memo)
	else
		puts "You must provide an amount and memo."
	end
else 
	display_help
end

